GroundGroupsBlue = {}
GroundGroupsBlue["M-1 Abrams-Vehicle_Armor_Heavy-2"] = {}
GroundGroupsBlue["M-1 Abrams-Vehicle_Armor_Heavy-2"]["Coalition"] = 2
GroundGroupsBlue["M-1 Abrams-Vehicle_Armor_Heavy-2"]["Type"] = "M-1 Abrams"
GroundGroupsBlue["M-1 Abrams-Vehicle_Armor_Heavy-2"]["Name"] = "M-1 Abrams-Vehicle_Armor_Heavy-2"
GroundGroupsBlue["M-1 Abrams-Vehicle_Armor_Heavy-2"]["Country"] = 80
GroundGroupsBlue["M-1 Abrams-Vehicle_Armor_Heavy-2"]["DCSGW_TASK"] = {}
GroundGroupsBlue["M-1 Abrams-Vehicle_Armor_Heavy-2"]["Position"] = {}
GroundGroupsBlue["M-1 Abrams-Vehicle_Armor_Heavy-2"]["Position"]["y"] = -86926.3671875
GroundGroupsBlue["M-1 Abrams-Vehicle_Armor_Heavy-2"]["Position"]["x"] = -246272.78125
GroundGroupsBlue["M-1 Abrams-Vehicle_Armor_Heavy-2"]["Units"] = {}
GroundGroupsBlue["M-1 Abrams-Vehicle_Armor_Heavy-2"]["Units"][1] = {}
GroundGroupsBlue["M-1 Abrams-Vehicle_Armor_Heavy-2"]["Units"][1]["y"] = -86926.3671875
GroundGroupsBlue["M-1 Abrams-Vehicle_Armor_Heavy-2"]["Units"][1]["x"] = -246272.78125
GroundGroupsBlue["M-1 Abrams-Vehicle_Armor_Heavy-2"]["Units"][1]["Name"] = "unit_M-1 Abrams-Vehicle_Armor_Heavy-2"
GroundGroupsBlue["M-1 Abrams-Vehicle_Armor_Heavy-2"]["Units"][1]["Life"] = 1
GroundGroupsBlue["M-1 Abrams-Vehicle_Armor_Heavy-2"]["Units"][1]["Heading"] = 0
GroundGroupsBlue["M-1 Abrams-Vehicle_Armor_Heavy-2"]["Units"][1]["Type"] = "M-1 Abrams"
GroundGroupsBlue["MLRS-Vehicle_Arty-1"] = {}
GroundGroupsBlue["MLRS-Vehicle_Arty-1"]["Coalition"] = 2
GroundGroupsBlue["MLRS-Vehicle_Arty-1"]["Type"] = "MLRS"
GroundGroupsBlue["MLRS-Vehicle_Arty-1"]["Name"] = "MLRS-Vehicle_Arty-1"
GroundGroupsBlue["MLRS-Vehicle_Arty-1"]["Country"] = 80
GroundGroupsBlue["MLRS-Vehicle_Arty-1"]["DCSGW_TASK"] = {}
GroundGroupsBlue["MLRS-Vehicle_Arty-1"]["Position"] = {}
GroundGroupsBlue["MLRS-Vehicle_Arty-1"]["Position"]["y"] = -86495.8203125
GroundGroupsBlue["MLRS-Vehicle_Arty-1"]["Position"]["x"] = -246309.671875
GroundGroupsBlue["MLRS-Vehicle_Arty-1"]["Units"] = {}
GroundGroupsBlue["MLRS-Vehicle_Arty-1"]["Units"][1] = {}
GroundGroupsBlue["MLRS-Vehicle_Arty-1"]["Units"][1]["y"] = -86495.8203125
GroundGroupsBlue["MLRS-Vehicle_Arty-1"]["Units"][1]["x"] = -246309.671875
GroundGroupsBlue["MLRS-Vehicle_Arty-1"]["Units"][1]["Name"] = "unit_MLRS-Vehicle_Arty-1"
GroundGroupsBlue["MLRS-Vehicle_Arty-1"]["Units"][1]["Life"] = 1
GroundGroupsBlue["MLRS-Vehicle_Arty-1"]["Units"][1]["Heading"] = 0
GroundGroupsBlue["MLRS-Vehicle_Arty-1"]["Units"][1]["Type"] = "MLRS"
GroundGroupsBlue["Ground-2"] = {}
GroundGroupsBlue["Ground-2"]["Coalition"] = 2
GroundGroupsBlue["Ground-2"]["Type"] = "SHERIDAN"
GroundGroupsBlue["Ground-2"]["Name"] = "Ground-2"
GroundGroupsBlue["Ground-2"]["Country"] = 80
GroundGroupsBlue["Ground-2"]["DCSGW_TASK"] = {}
GroundGroupsBlue["Ground-2"]["Position"] = {}
GroundGroupsBlue["Ground-2"]["Position"]["y"] = -86379.1875
GroundGroupsBlue["Ground-2"]["Position"]["x"] = -246419.109375
GroundGroupsBlue["Ground-2"]["Units"] = {}
GroundGroupsBlue["Ground-2"]["Units"][1] = {}
GroundGroupsBlue["Ground-2"]["Units"][1]["y"] = -86379.1875
GroundGroupsBlue["Ground-2"]["Units"][1]["x"] = -246419.109375
GroundGroupsBlue["Ground-2"]["Units"][1]["Name"] = "Ground-2-1"
GroundGroupsBlue["Ground-2"]["Units"][1]["Life"] = 1
GroundGroupsBlue["Ground-2"]["Units"][1]["Heading"] = 64.979150898717
GroundGroupsBlue["Ground-2"]["Units"][1]["Type"] = "SHERIDAN"
GroundGroupsBlue["MLRS-Vehicle_Arty-2"] = {}
GroundGroupsBlue["MLRS-Vehicle_Arty-2"]["Coalition"] = 2
GroundGroupsBlue["MLRS-Vehicle_Arty-2"]["Type"] = "MLRS"
GroundGroupsBlue["MLRS-Vehicle_Arty-2"]["Name"] = "MLRS-Vehicle_Arty-2"
GroundGroupsBlue["MLRS-Vehicle_Arty-2"]["Country"] = 80
GroundGroupsBlue["MLRS-Vehicle_Arty-2"]["DCSGW_TASK"] = {}
GroundGroupsBlue["MLRS-Vehicle_Arty-2"]["Position"] = {}
GroundGroupsBlue["MLRS-Vehicle_Arty-2"]["Position"]["y"] = -85511.6484375
GroundGroupsBlue["MLRS-Vehicle_Arty-2"]["Position"]["x"] = -246668.8125
GroundGroupsBlue["MLRS-Vehicle_Arty-2"]["Units"] = {}
GroundGroupsBlue["MLRS-Vehicle_Arty-2"]["Units"][1] = {}
GroundGroupsBlue["MLRS-Vehicle_Arty-2"]["Units"][1]["y"] = -85511.6484375
GroundGroupsBlue["MLRS-Vehicle_Arty-2"]["Units"][1]["x"] = -246668.8125
GroundGroupsBlue["MLRS-Vehicle_Arty-2"]["Units"][1]["Name"] = "unit_MLRS-Vehicle_Arty-2"
GroundGroupsBlue["MLRS-Vehicle_Arty-2"]["Units"][1]["Life"] = 1
GroundGroupsBlue["MLRS-Vehicle_Arty-2"]["Units"][1]["Heading"] = 0
GroundGroupsBlue["MLRS-Vehicle_Arty-2"]["Units"][1]["Type"] = "MLRS"
GroundGroupsBlue["Ground-1"] = {}
GroundGroupsBlue["Ground-1"]["Coalition"] = 2
GroundGroupsBlue["Ground-1"]["Type"] = "M2A1_halftrack"
GroundGroupsBlue["Ground-1"]["Name"] = "Ground-1"
GroundGroupsBlue["Ground-1"]["Country"] = 80
GroundGroupsBlue["Ground-1"]["DCSGW_TASK"] = {}
GroundGroupsBlue["Ground-1"]["Position"] = {}
GroundGroupsBlue["Ground-1"]["Position"]["y"] = -86628.601562548
GroundGroupsBlue["Ground-1"]["Position"]["x"] = -246127.89062504
GroundGroupsBlue["Ground-1"]["Units"] = {}
GroundGroupsBlue["Ground-1"]["Units"][1] = {}
GroundGroupsBlue["Ground-1"]["Units"][1]["y"] = -86628.601562548
GroundGroupsBlue["Ground-1"]["Units"][1]["x"] = -246127.89062504
GroundGroupsBlue["Ground-1"]["Units"][1]["Name"] = "Ground-1-3"
GroundGroupsBlue["Ground-1"]["Units"][1]["Life"] = 1
GroundGroupsBlue["Ground-1"]["Units"][1]["Heading"] = 233.1727133966
GroundGroupsBlue["Ground-1"]["Units"][1]["Type"] = "M2A1_halftrack"
GroundGroupsBlue["Ground-1"]["Units"][2] = {}
GroundGroupsBlue["Ground-1"]["Units"][2]["y"] = -86630.695312507
GroundGroupsBlue["Ground-1"]["Units"][2]["x"] = -246148.79687506
GroundGroupsBlue["Ground-1"]["Units"][2]["Name"] = "Ground-1-2"
GroundGroupsBlue["Ground-1"]["Units"][2]["Life"] = 1
GroundGroupsBlue["Ground-1"]["Units"][2]["Heading"] = 186.78713588681
GroundGroupsBlue["Ground-1"]["Units"][2]["Type"] = "M2A1_halftrack"
GroundGroupsBlue["Ground-1"]["Units"][3] = {}
GroundGroupsBlue["Ground-1"]["Units"][3]["y"] = -86668.203124955
GroundGroupsBlue["Ground-1"]["Units"][3]["x"] = -246220.34375004
GroundGroupsBlue["Ground-1"]["Units"][3]["Name"] = "Ground-1-1"
GroundGroupsBlue["Ground-1"]["Units"][3]["Life"] = 1
GroundGroupsBlue["Ground-1"]["Units"][3]["Heading"] = 131.96385522041
GroundGroupsBlue["Ground-1"]["Units"][3]["Type"] = "M2A1_halftrack"
