GroundGroupsDestroyed = {}
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_76"] = {}
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_76"]["Coalition"] = 2
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_76"]["x"] = -243903.07427523
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_76"]["Name"] = "Leclerc_XXI-Vehicle_Armor_Heavy-unitID_76"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_76"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_76"]["y"] = -87625.873127753
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_76"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_46"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_46"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_46"]["x"] = -245769.77849908
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_46"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_46"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_46"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_46"]["y"] = -70590.305600406
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_46"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_47"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_47"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_47"]["x"] = -245809.50340957
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_47"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_47"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_47"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_47"]["y"] = -71390.115218637
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_47"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_52"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_52"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_52"]["x"] = -245800.43021903
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_52"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_52"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_52"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_52"]["y"] = -71366.264664167
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_52"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_39"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_39"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_39"]["x"] = -245499.0625
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_39"]["Name"] = "MLRS-Vehicle_Arty-unitID_39"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_39"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_39"]["y"] = -87336.703125
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_39"]["Dead"] = true
GroundGroupsDestroyed["Ground-3-4"] = {}
GroundGroupsDestroyed["Ground-3-4"]["Coalition"] = 1
GroundGroupsDestroyed["Ground-3-4"]["x"] = -244069.515625
GroundGroupsDestroyed["Ground-3-4"]["Name"] = "Ground-3-4"
GroundGroupsDestroyed["Ground-3-4"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Ground-3-4"]["y"] = -87558.3671875
GroundGroupsDestroyed["Ground-3-4"]["Dead"] = true
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_67"] = {}
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_67"]["Coalition"] = 2
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_67"]["x"] = -244684.79981193
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_67"]["Name"] = "M-113-Vehicle_Armor_Light-unitID_67"
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_67"]["Type"] = "M-113"
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_67"]["y"] = -87442.078801765
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_67"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_49"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_49"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_49"]["x"] = -246452.26528473
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_49"]["Name"] = "MLRS-Vehicle_Arty-unitID_49"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_49"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_49"]["y"] = -85772.684758109
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_49"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_69"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_69"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_69"]["x"] = -245629.80080406
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_69"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_69"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_69"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_69"]["y"] = -71246.828202433
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_69"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_52"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_52"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_52"]["x"] = -246572.59541325
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_52"]["Name"] = "MLRS-Vehicle_Arty-unitID_52"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_52"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_52"]["y"] = -85793.440752822
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_52"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_54"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_54"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_54"]["x"] = -245824.47497126
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_54"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_54"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_54"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_54"]["y"] = -71334.49580896
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_54"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_55"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_55"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_55"]["x"] = -245825.39140209
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_55"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_55"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_55"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_55"]["y"] = -71326.856928877
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_55"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_70"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_70"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_70"]["x"] = -245630.99954478
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_70"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_70"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_70"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_70"]["y"] = -71251.836060428
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_70"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_74"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_74"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_74"]["x"] = -245612.64668956
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_74"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_74"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_74"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_74"]["y"] = -71231.954447555
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_74"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_71"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_71"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_71"]["x"] = -245612.95852071
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_71"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_71"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_71"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_71"]["y"] = -71249.289614046
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_71"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_73"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_73"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_73"]["x"] = -245617.57912597
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_73"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_73"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_73"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_73"]["y"] = -71248.002308291
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_73"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_56"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_56"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_56"]["x"] = -246664.578125
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_56"]["Name"] = "MLRS-Vehicle_Arty-unitID_56"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_56"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_56"]["y"] = -85823.1171875
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_56"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_68"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_68"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_68"]["x"] = -245615.60278678
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_68"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_68"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_68"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_68"]["y"] = -71255.01491227
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_68"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_72"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_72"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_72"]["x"] = -245606.27785892
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_72"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_72"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_72"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_72"]["y"] = -71224.960076962
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_72"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_75"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_75"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_75"]["x"] = -245620.85925769
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_75"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_75"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_75"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_75"]["y"] = -71243.131630609
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_75"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_76"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_76"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_76"]["x"] = -245614.29733298
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_76"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_76"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_76"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_76"]["y"] = -71219.260976051
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_76"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_35"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_35"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_35"]["x"] = -245837.30985291
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_35"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_35"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_35"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_35"]["y"] = -70933.366898081
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_35"]["Dead"] = true
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_60"] = {}
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_60"]["Coalition"] = 2
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_60"]["x"] = -244486.65592501
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_60"]["Name"] = "Leclerc_XXI-Vehicle_Armor_Heavy-unitID_60"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_60"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_60"]["y"] = -87671.339206899
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_60"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_50"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_50"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_50"]["x"] = -246491.83777266
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_50"]["Name"] = "MLRS-Vehicle_Arty-unitID_50"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_50"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_50"]["y"] = -85807.393761602
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_50"]["Dead"] = true
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_77"] = {}
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_77"]["Coalition"] = 2
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_77"]["x"] = -243938.22548251
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_77"]["Name"] = "Leclerc_XXI-Vehicle_Armor_Heavy-unitID_77"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_77"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_77"]["y"] = -87592.723234112
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_77"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_34"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_34"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_34"]["x"] = -245823.19682111
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_34"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_34"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_34"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_34"]["y"] = -70989.720874923
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_34"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_31"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_31"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_31"]["x"] = -245818.59864132
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_31"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_31"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_31"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_31"]["y"] = -70986.136136064
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_31"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_28"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_28"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_28"]["x"] = -245816.82445017
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_28"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_28"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_28"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_28"]["y"] = -70984.626009347
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_28"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_40"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_40"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_40"]["x"] = -245769.27405905
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_40"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_40"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_40"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_40"]["y"] = -70609.745549537
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_40"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_37"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_37"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_37"]["x"] = -245769.57108527
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_37"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_37"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_37"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_37"]["y"] = -70628.932426836
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_37"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_55"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_55"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_55"]["x"] = -246245.06308967
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_55"]["Name"] = "MLRS-Vehicle_Arty-unitID_55"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_55"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_55"]["y"] = -85385.334650241
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_55"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_45"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_45"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_45"]["x"] = -245777.21206023
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_45"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_45"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_45"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_45"]["y"] = -70591.328158979
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_45"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_39"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_39"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_39"]["x"] = -245779.23125533
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_39"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_39"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_39"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_39"]["y"] = -70624.948012602
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_39"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_42"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_42"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_42"]["x"] = -245777.6574229
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_42"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_42"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_42"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_42"]["y"] = -70605.526153463
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_42"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_50"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_50"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_50"]["x"] = -245815.31743162
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_50"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_50"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_50"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_50"]["y"] = -71374.854644569
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_50"]["Dead"] = true
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_78"] = {}
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_78"]["Coalition"] = 2
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_78"]["x"] = -243763.69405634
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_78"]["Name"] = "Leclerc_XXI-Vehicle_Armor_Heavy-unitID_78"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_78"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_78"]["y"] = -87646.234811258
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_78"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_27"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_27"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_27"]["x"] = -245809.8593182
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_27"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_27"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_27"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_27"]["y"] = -70992.242653535
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_27"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_67"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_67"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_67"]["x"] = -245624.7261431
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_67"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_67"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_67"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_67"]["y"] = -71255.237233414
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_67"]["Dead"] = true
GroundGroupsDestroyed["Ground-1-1"] = {}
GroundGroupsDestroyed["Ground-1-1"]["Coalition"] = 2
GroundGroupsDestroyed["Ground-1-1"]["x"] = -246349.62500001
GroundGroupsDestroyed["Ground-1-1"]["Name"] = "Ground-1-1"
GroundGroupsDestroyed["Ground-1-1"]["Type"] = "InsurgentPickUp"
GroundGroupsDestroyed["Ground-1-1"]["y"] = -82915.390625047
GroundGroupsDestroyed["Ground-1-1"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_49"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_49"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_49"]["x"] = -245812.968536
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_49"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_49"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_49"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_49"]["y"] = -71385.717145538
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_49"]["Dead"] = true
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_66"] = {}
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_66"]["Coalition"] = 2
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_66"]["x"] = -244666.58853695
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_66"]["Name"] = "M-113-Vehicle_Armor_Light-unitID_66"
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_66"]["Type"] = "M-113"
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_66"]["y"] = -87481.845013039
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_66"]["Dead"] = true
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_58"] = {}
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_58"]["Coalition"] = 2
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_58"]["x"] = -244505.61441188
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_58"]["Name"] = "Leclerc_XXI-Vehicle_Armor_Heavy-unitID_58"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_58"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_58"]["y"] = -87413.890667372
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_58"]["Dead"] = true
GroundGroupsDestroyed["Ground-3-2"] = {}
GroundGroupsDestroyed["Ground-3-2"]["Coalition"] = 1
GroundGroupsDestroyed["Ground-3-2"]["x"] = -244120.1875
GroundGroupsDestroyed["Ground-3-2"]["Name"] = "Ground-3-2"
GroundGroupsDestroyed["Ground-3-2"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Ground-3-2"]["y"] = -87542.09375
GroundGroupsDestroyed["Ground-3-2"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_54"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_54"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_54"]["x"] = -246423.0138261
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_54"]["Name"] = "MLRS-Vehicle_Arty-unitID_54"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_54"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_54"]["y"] = -85804.599802442
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_54"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_51"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_51"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_51"]["x"] = -245817.57988891
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_51"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_51"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_51"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_51"]["y"] = -71363.89008617
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_51"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_48"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_48"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_48"]["x"] = -245809.80771958
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_48"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_48"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_48"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_48"]["y"] = -71380.116413679
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_48"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_53"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_53"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_53"]["x"] = -245822.87135438
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_53"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_53"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_53"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_53"]["y"] = -71346.805501113
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_53"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_16"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_16"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_16"]["x"] = -245310.140625
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_16"]["Name"] = "MLRS-Vehicle_Arty-unitID_16"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_16"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_16"]["y"] = -87291.1875
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_16"]["Dead"] = true
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_59"] = {}
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_59"]["Coalition"] = 2
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_59"]["x"] = -244593.8790296
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_59"]["Name"] = "Leclerc_XXI-Vehicle_Armor_Heavy-unitID_59"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_59"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_59"]["y"] = -87645.369591535
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_59"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_53"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_53"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_53"]["x"] = -246360.203125
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_53"]["Name"] = "MLRS-Vehicle_Arty-unitID_53"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_53"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_53"]["y"] = -85803.765625
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_53"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_51"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_51"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_51"]["x"] = -246400.59866544
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_51"]["Name"] = "MLRS-Vehicle_Arty-unitID_51"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_51"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_51"]["y"] = -85774.057218333
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_51"]["Dead"] = true
GroundGroupsDestroyed["Ground-3-3"] = {}
GroundGroupsDestroyed["Ground-3-3"]["Coalition"] = 1
GroundGroupsDestroyed["Ground-3-3"]["x"] = -244098.515625
GroundGroupsDestroyed["Ground-3-3"]["Name"] = "Ground-3-3"
GroundGroupsDestroyed["Ground-3-3"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Ground-3-3"]["y"] = -87553.7578125
GroundGroupsDestroyed["Ground-3-3"]["Dead"] = true
GroundGroupsDestroyed["Ground-3-1"] = {}
GroundGroupsDestroyed["Ground-3-1"]["Coalition"] = 1
GroundGroupsDestroyed["Ground-3-1"]["x"] = -244136.015625
GroundGroupsDestroyed["Ground-3-1"]["Name"] = "Ground-3-1"
GroundGroupsDestroyed["Ground-3-1"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Ground-3-1"]["y"] = -87551.1171875
GroundGroupsDestroyed["Ground-3-1"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_35"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_35"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_35"]["x"] = -245426.859375
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_35"]["Name"] = "MLRS-Vehicle_Arty-unitID_35"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_35"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_35"]["y"] = -87572.84375
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_35"]["Dead"] = true
