GroundGroupsDestroyed = {}
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_94"] = {}
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_94"]["Coalition"] = 2
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_94"]["x"] = -245628.3061921
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_94"]["Name"] = "Leclerc_XXI-Vehicle_Armor_Heavy-unitID_94"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_94"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_94"]["y"] = -87609.933158648
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_94"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_46"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_46"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_46"]["x"] = -245769.77849908
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_46"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_46"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_46"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_46"]["y"] = -70590.305600406
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_46"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_106"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_106"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_106"]["x"] = -246593.71922877
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_106"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_106"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_106"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_106"]["y"] = -86878.815789622
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_106"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_32"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_32"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_32"]["x"] = -245821.0625
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_32"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_32"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_32"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_32"]["y"] = -70993.9921875
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_32"]["Dead"] = true
GroundGroupsDestroyed["Ground-3-4"] = {}
GroundGroupsDestroyed["Ground-3-4"]["Coalition"] = 1
GroundGroupsDestroyed["Ground-3-4"]["x"] = -244069.515625
GroundGroupsDestroyed["Ground-3-4"]["Name"] = "Ground-3-4"
GroundGroupsDestroyed["Ground-3-4"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Ground-3-4"]["y"] = -87558.3671875
GroundGroupsDestroyed["Ground-3-4"]["Dead"] = true
GroundGroupsDestroyed["UAZ-469|Red|26111"] = {}
GroundGroupsDestroyed["UAZ-469|Red|26111"]["Coalition"] = 1
GroundGroupsDestroyed["UAZ-469|Red|26111"]["x"] = -242508.03111908
GroundGroupsDestroyed["UAZ-469|Red|26111"]["Name"] = "UAZ-469|Red|26111"
GroundGroupsDestroyed["UAZ-469|Red|26111"]["Type"] = "UAZ-469"
GroundGroupsDestroyed["UAZ-469|Red|26111"]["y"] = -87756.007850087
GroundGroupsDestroyed["UAZ-469|Red|26111"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_49"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_49"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_49"]["x"] = -246452.26528473
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_49"]["Name"] = "MLRS-Vehicle_Arty-unitID_49"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_49"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_49"]["y"] = -85772.684758109
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_49"]["Dead"] = true
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_93"] = {}
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_93"]["Coalition"] = 2
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_93"]["x"] = -245589.67141149
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_93"]["Name"] = "Leclerc_XXI-Vehicle_Armor_Heavy-unitID_93"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_93"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_93"]["y"] = -87465.141959254
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_93"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_52"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_52"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_52"]["x"] = -246572.59541325
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_52"]["Name"] = "MLRS-Vehicle_Arty-unitID_52"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_52"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_52"]["y"] = -85793.440752822
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_52"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_104"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_104"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_104"]["x"] = -246739.69872466
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_104"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_104"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_104"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_104"]["y"] = -86724.721250164
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_104"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_109"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_109"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_109"]["x"] = -246208.07820209
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_109"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_109"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_109"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_109"]["y"] = -87029.15611616
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_109"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_53"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_53"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_53"]["x"] = -245822.87135438
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_53"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_53"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_53"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_53"]["y"] = -71346.805501113
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_53"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_50"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_50"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_50"]["x"] = -246491.83777266
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_50"]["Name"] = "MLRS-Vehicle_Arty-unitID_50"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_50"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_50"]["y"] = -85807.393761602
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_50"]["Dead"] = true
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_77"] = {}
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_77"]["Coalition"] = 2
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_77"]["x"] = -243938.22548251
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_77"]["Name"] = "Leclerc_XXI-Vehicle_Armor_Heavy-unitID_77"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_77"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_77"]["y"] = -87592.723234112
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_77"]["Dead"] = true
GroundGroupsDestroyed["HQ"] = {}
GroundGroupsDestroyed["HQ"]["Coalition"] = 2
GroundGroupsDestroyed["HQ"]["x"] = -245444.38997197
GroundGroupsDestroyed["HQ"]["Name"] = "HQ"
GroundGroupsDestroyed["HQ"]["Type"] = "Tigr_233036"
GroundGroupsDestroyed["HQ"]["y"] = -84388.138191267
GroundGroupsDestroyed["HQ"]["Dead"] = true
GroundGroupsDestroyed["Tigr_233036|Blue|3297"] = {}
GroundGroupsDestroyed["Tigr_233036|Blue|3297"]["Coalition"] = 2
GroundGroupsDestroyed["Tigr_233036|Blue|3297"]["x"] = -246158.90322029
GroundGroupsDestroyed["Tigr_233036|Blue|3297"]["Name"] = "Tigr_233036|Blue|3297"
GroundGroupsDestroyed["Tigr_233036|Blue|3297"]["Type"] = "Tigr_233036"
GroundGroupsDestroyed["Tigr_233036|Blue|3297"]["y"] = -84230.817892839
GroundGroupsDestroyed["Tigr_233036|Blue|3297"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_70"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_70"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_70"]["x"] = -245630.99954478
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_70"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_70"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_70"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_70"]["y"] = -71251.836060428
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_70"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_81"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_81"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_81"]["x"] = -246391.94205248
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_81"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_81"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_81"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_81"]["y"] = -86802.146284787
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_81"]["Dead"] = true
GroundGroupsDestroyed["Tigr_233036|Blue|3398"] = {}
GroundGroupsDestroyed["Tigr_233036|Blue|3398"]["Coalition"] = 2
GroundGroupsDestroyed["Tigr_233036|Blue|3398"]["x"] = -245203.9702849
GroundGroupsDestroyed["Tigr_233036|Blue|3398"]["Name"] = "Tigr_233036|Blue|3398"
GroundGroupsDestroyed["Tigr_233036|Blue|3398"]["Type"] = "Tigr_233036"
GroundGroupsDestroyed["Tigr_233036|Blue|3398"]["y"] = -84452.853752417
GroundGroupsDestroyed["Tigr_233036|Blue|3398"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_55"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_55"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_55"]["x"] = -246245.06308967
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_55"]["Name"] = "MLRS-Vehicle_Arty-unitID_55"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_55"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_55"]["y"] = -85385.334650241
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_55"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_83"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_83"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_83"]["x"] = -246464.46844784
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_83"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_83"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_83"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_83"]["y"] = -86594.453125
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_83"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_90"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_90"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_90"]["x"] = -246465.40078483
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_90"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_90"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_90"]["y"] = -87137.844328352
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_90"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_29"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_29"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_29"]["x"] = -245839.59375
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_29"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_29"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_29"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_29"]["y"] = -70986.265625
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_29"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_39"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_39"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_39"]["x"] = -245779.23125533
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_39"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_39"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_39"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_39"]["y"] = -70624.948012602
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_39"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_62"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_62"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_62"]["x"] = -245188.859375
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_62"]["Name"] = "MLRS-Vehicle_Arty-unitID_62"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_62"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_62"]["y"] = -87390.078125
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_62"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_48"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_48"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_48"]["x"] = -245809.80771958
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_48"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_48"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_48"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_48"]["y"] = -71380.116413679
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_48"]["Dead"] = true
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_58"] = {}
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_58"]["Coalition"] = 2
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_58"]["x"] = -244505.61441188
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_58"]["Name"] = "Leclerc_XXI-Vehicle_Armor_Heavy-unitID_58"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_58"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_58"]["y"] = -87413.890667372
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_58"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_82"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_82"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_82"]["x"] = -246416.90583942
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_82"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_82"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_82"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_82"]["y"] = -86840.505729548
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_82"]["Dead"] = true
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_89"] = {}
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_89"]["Coalition"] = 2
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_89"]["x"] = -245357.04687503
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_89"]["Name"] = "Hummer-Vehicle_Logistic-unitID_89"
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_89"]["Type"] = "Hummer"
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_89"]["y"] = -87310.804687539
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_89"]["Dead"] = true
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_90"] = {}
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_90"]["Coalition"] = 2
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_90"]["x"] = -245357.04687501
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_90"]["Name"] = "Hummer-Vehicle_Logistic-unitID_90"
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_90"]["Type"] = "Hummer"
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_90"]["y"] = -87300.804687452
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_90"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_49"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_49"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_49"]["x"] = -245812.968536
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_49"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_49"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_49"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_49"]["y"] = -71385.717145538
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_49"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_16"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_16"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_16"]["x"] = -245310.140625
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_16"]["Name"] = "MLRS-Vehicle_Arty-unitID_16"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_16"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_16"]["y"] = -87291.1875
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_16"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_69"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_69"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_69"]["x"] = -245629.80080406
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_69"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_69"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_69"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_69"]["y"] = -71246.828202433
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_69"]["Dead"] = true
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_78"] = {}
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_78"]["Coalition"] = 2
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_78"]["x"] = -243763.69405634
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_78"]["Name"] = "Leclerc_XXI-Vehicle_Armor_Heavy-unitID_78"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_78"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_78"]["y"] = -87646.234811258
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_78"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_68"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_68"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_68"]["x"] = -245615.60278678
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_68"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_68"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_68"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_68"]["y"] = -71255.01491227
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_68"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_80"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_80"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_80"]["x"] = -246432.19511157
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_80"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_80"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_80"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_80"]["y"] = -86973.218162724
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_80"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_91"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_91"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_91"]["x"] = -246464.4308543
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_91"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_91"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_91"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_91"]["y"] = -87128.230804221
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_91"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_56"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_56"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_56"]["x"] = -246664.578125
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_56"]["Name"] = "MLRS-Vehicle_Arty-unitID_56"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_56"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_56"]["y"] = -85823.1171875
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_56"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_51"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_51"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_51"]["x"] = -245817.57988891
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_51"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_51"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_51"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_51"]["y"] = -71363.89008617
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_51"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_51"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_51"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_51"]["x"] = -246400.59866544
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_51"]["Name"] = "MLRS-Vehicle_Arty-unitID_51"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_51"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_51"]["y"] = -85774.057218333
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_51"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_39"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_39"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_39"]["x"] = -245499.0625
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_39"]["Name"] = "MLRS-Vehicle_Arty-unitID_39"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_39"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_39"]["y"] = -87336.703125
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_39"]["Dead"] = true
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_83"] = {}
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_83"]["Coalition"] = 2
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_83"]["x"] = -245276.57812498
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_83"]["Name"] = "Hummer-Vehicle_Logistic-unitID_83"
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_83"]["Type"] = "Hummer"
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_83"]["y"] = -87344.101562547
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_83"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_96"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_96"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_96"]["x"] = -246709.25380119
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_96"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_96"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_96"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_96"]["y"] = -86755.501318256
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_96"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_108"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_108"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_108"]["x"] = -245352.85392527
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_108"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_108"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_108"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_108"]["y"] = -87243.357310142
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_108"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_45"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_45"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_45"]["x"] = -245777.21875
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_45"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_45"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_45"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_45"]["y"] = -70591.328125
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_45"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_89"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_89"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_89"]["x"] = -246465.40071537
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_89"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_89"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_89"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_89"]["y"] = -87147.844268187
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_89"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_95"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_95"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_95"]["x"] = -246675.36643017
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_95"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_95"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_95"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_95"]["y"] = -86878.456343654
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_95"]["Dead"] = true
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_88"] = {}
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_88"]["Coalition"] = 2
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_88"]["x"] = -245357.04687501
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_88"]["Name"] = "Hummer-Vehicle_Logistic-unitID_88"
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_88"]["Type"] = "Hummer"
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_88"]["y"] = -87320.804687452
GroundGroupsDestroyed["Hummer-Vehicle_Logistic-unitID_88"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_86"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_86"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_86"]["x"] = -246497.60439091
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_86"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_86"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_86"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_86"]["y"] = -86719.099867861
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_86"]["Dead"] = true
GroundGroupsDestroyed["Ground-3-2"] = {}
GroundGroupsDestroyed["Ground-3-2"]["Coalition"] = 1
GroundGroupsDestroyed["Ground-3-2"]["x"] = -244120.1875
GroundGroupsDestroyed["Ground-3-2"]["Name"] = "Ground-3-2"
GroundGroupsDestroyed["Ground-3-2"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Ground-3-2"]["y"] = -87542.09375
GroundGroupsDestroyed["Ground-3-2"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_98"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_98"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_98"]["x"] = -246640.80178659
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_98"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_98"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_98"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_98"]["y"] = -86842.235737113
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_98"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_54"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_54"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_54"]["x"] = -245824.47497126
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_54"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_54"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_54"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_54"]["y"] = -71334.49580896
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_54"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_102"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_102"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_102"]["x"] = -245634.45764426
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_102"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_102"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_102"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_102"]["y"] = -87257.927134138
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_102"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_110"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_110"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_110"]["x"] = -245983.62476085
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_110"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_110"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_110"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_110"]["y"] = -86974.031342379
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_110"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_101"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_101"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_101"]["x"] = -245619.95723238
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_101"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_101"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_101"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_101"]["y"] = -87222.149759945
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_101"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_55"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_55"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_55"]["x"] = -245825.39140209
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_55"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_55"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_55"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_55"]["y"] = -71326.856928877
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_55"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_50"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_50"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_50"]["x"] = -245815.31743162
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_50"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_50"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_50"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_50"]["y"] = -71374.854644569
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_50"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_100"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_100"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_100"]["x"] = -245939.77863075
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_100"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_100"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_100"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_100"]["y"] = -87053.829060474
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_100"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_105"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_105"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_105"]["x"] = -246635.10701532
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_105"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_105"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_105"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_105"]["y"] = -86838.057440684
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_105"]["Dead"] = true
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_67"] = {}
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_67"]["Coalition"] = 2
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_67"]["x"] = -244684.79981193
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_67"]["Name"] = "M-113-Vehicle_Armor_Light-unitID_67"
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_67"]["Type"] = "M-113"
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_67"]["y"] = -87442.078801765
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_67"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_85"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_85"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_85"]["x"] = -246464.46865088
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_85"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_85"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_85"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_85"]["y"] = -86574.453125
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_85"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_52"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_52"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_52"]["x"] = -245800.43021903
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_52"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_52"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_52"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_52"]["y"] = -71366.264664167
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_52"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_47"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_47"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_47"]["x"] = -245809.50340957
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_47"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_47"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_47"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_47"]["y"] = -71390.115218637
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_47"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_34"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_34"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_34"]["x"] = -245823.19682111
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_34"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_34"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_34"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_34"]["y"] = -70989.720874923
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_34"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_75"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_75"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_75"]["x"] = -245620.85925769
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_75"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_75"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_75"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_75"]["y"] = -71243.131630609
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_75"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_37"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_37"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_37"]["x"] = -245769.57108527
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_37"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_37"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_37"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_37"]["y"] = -70628.932426836
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_37"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_79"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_79"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_79"]["x"] = -246387.07947901
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_79"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_79"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_79"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_79"]["y"] = -86874.990367974
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_79"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_92"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_92"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_92"]["x"] = -246465.40089714
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_92"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_92"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_92"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_92"]["y"] = -87117.844342468
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_92"]["Dead"] = true
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_76"] = {}
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_76"]["Coalition"] = 2
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_76"]["x"] = -243903.07427523
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_76"]["Name"] = "Leclerc_XXI-Vehicle_Armor_Heavy-unitID_76"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_76"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_76"]["y"] = -87625.873127753
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_76"]["Dead"] = true
GroundGroupsDestroyed["Ground-3-1"] = {}
GroundGroupsDestroyed["Ground-3-1"]["Coalition"] = 1
GroundGroupsDestroyed["Ground-3-1"]["x"] = -244136.015625
GroundGroupsDestroyed["Ground-3-1"]["Name"] = "Ground-3-1"
GroundGroupsDestroyed["Ground-3-1"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Ground-3-1"]["y"] = -87551.1171875
GroundGroupsDestroyed["Ground-3-1"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_76"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_76"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_76"]["x"] = -245614.29733298
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_76"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_76"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_76"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_76"]["y"] = -71219.260976051
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_76"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_72"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_72"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_72"]["x"] = -245606.27785892
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_72"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_72"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_72"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_72"]["y"] = -71224.960076962
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_72"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_42"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_42"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_42"]["x"] = -245527.84375
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_42"]["Name"] = "MLRS-Vehicle_Arty-unitID_42"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_42"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_42"]["y"] = -87297.1953125
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_42"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_84"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_84"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_84"]["x"] = -246423.83671704
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_84"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_84"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_84"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_84"]["y"] = -86839.80507552
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_84"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_94"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_94"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_94"]["x"] = -246465.40085656
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_94"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_94"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_94"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_94"]["y"] = -87097.844337347
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_94"]["Dead"] = true
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_60"] = {}
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_60"]["Coalition"] = 2
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_60"]["x"] = -244486.65592501
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_60"]["Name"] = "Leclerc_XXI-Vehicle_Armor_Heavy-unitID_60"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_60"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_60"]["y"] = -87671.339206899
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_60"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_67"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_67"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_67"]["x"] = -245624.7261431
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_67"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_67"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_67"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_67"]["y"] = -71255.237233414
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_67"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_28"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_28"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_28"]["x"] = -245816.82445017
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_28"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_28"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_28"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_28"]["y"] = -70984.626009347
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_28"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_77"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_77"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_77"]["x"] = -246453.22549223
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_77"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_77"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_77"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_77"]["y"] = -86945.535231318
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_77"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_42"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_42"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_42"]["x"] = -245777.65625
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_42"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_42"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_42"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_42"]["y"] = -70605.5234375
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_42"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_36"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_36"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_36"]["x"] = -245820.609375
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_36"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_36"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_36"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_36"]["y"] = -70998.9609375
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_36"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_99"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_99"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_99"]["x"] = -245714.32923586
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_99"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_99"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_99"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_99"]["y"] = -87017.170827401
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_99"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_27"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_27"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_27"]["x"] = -245809.8593182
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_27"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_27"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_27"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_27"]["y"] = -70992.242653535
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_27"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_54"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_54"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_54"]["x"] = -246423.0138261
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_54"]["Name"] = "MLRS-Vehicle_Arty-unitID_54"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_54"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_54"]["y"] = -85804.599802442
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_54"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_78"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_78"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_78"]["x"] = -246391.71200028
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_78"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_78"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_78"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_78"]["y"] = -86895.88737433
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_78"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_35"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_35"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_35"]["x"] = -245820.609375
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_35"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_35"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_35"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_35"]["y"] = -70998.9609375
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_35"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_74"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_74"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_74"]["x"] = -245612.64668956
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_74"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_74"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_74"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_74"]["y"] = -71231.954447555
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_74"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_40"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_40"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_40"]["x"] = -245769.27405905
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_40"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_40"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_40"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_40"]["y"] = -70609.745549537
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_40"]["Dead"] = true
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_92"] = {}
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_92"]["Coalition"] = 2
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_92"]["x"] = -245642.41810623
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_92"]["Name"] = "Leclerc_XXI-Vehicle_Armor_Heavy-unitID_92"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_92"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_92"]["y"] = -87549.918321934
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_92"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_97"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_97"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_97"]["x"] = -246642.34990334
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_97"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_97"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_97"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_97"]["y"] = -86861.224564579
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_97"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_103"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_103"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_103"]["x"] = -246780.97309358
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_103"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_103"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_103"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_103"]["y"] = -86686.322438789
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_103"]["Dead"] = true
GroundGroupsDestroyed["Ground-1-1"] = {}
GroundGroupsDestroyed["Ground-1-1"]["Coalition"] = 2
GroundGroupsDestroyed["Ground-1-1"]["x"] = -246349.62500001
GroundGroupsDestroyed["Ground-1-1"]["Name"] = "Ground-1-1"
GroundGroupsDestroyed["Ground-1-1"]["Type"] = "InsurgentPickUp"
GroundGroupsDestroyed["Ground-1-1"]["y"] = -82915.390625047
GroundGroupsDestroyed["Ground-1-1"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_73"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_73"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_73"]["x"] = -245617.57912597
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_73"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_73"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_73"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_73"]["y"] = -71248.002308291
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_73"]["Dead"] = true
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_66"] = {}
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_66"]["Coalition"] = 2
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_66"]["x"] = -244666.58853695
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_66"]["Name"] = "M-113-Vehicle_Armor_Light-unitID_66"
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_66"]["Type"] = "M-113"
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_66"]["y"] = -87481.845013039
GroundGroupsDestroyed["M-113-Vehicle_Armor_Light-unitID_66"]["Dead"] = true
GroundGroupsDestroyed["Ground-2-1"] = {}
GroundGroupsDestroyed["Ground-2-1"]["Coalition"] = 2
GroundGroupsDestroyed["Ground-2-1"]["x"] = -244234.37499997
GroundGroupsDestroyed["Ground-2-1"]["Name"] = "Ground-2-1"
GroundGroupsDestroyed["Ground-2-1"]["Type"] = "InsurgentPickUp"
GroundGroupsDestroyed["Ground-2-1"]["y"] = -84256.843749964
GroundGroupsDestroyed["Ground-2-1"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_87"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_87"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_87"]["x"] = -246465.23665721
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_87"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_87"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_87"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_87"]["y"] = -87167.822433754
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_87"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_88"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_88"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_88"]["x"] = -246465.40071602
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_88"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_88"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_88"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_88"]["y"] = -87157.844331112
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_88"]["Dead"] = true
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_93"] = {}
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_93"]["Coalition"] = 1
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_93"]["x"] = -246465.40076477
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_93"]["Name"] = "T-90-Vehicle_Armor_Heavy-unitID_93"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_93"]["Type"] = "T-90"
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_93"]["y"] = -87107.844325829
GroundGroupsDestroyed["T-90-Vehicle_Armor_Heavy-unitID_93"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_40"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_40"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_40"]["x"] = -245555.421875
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_40"]["Name"] = "MLRS-Vehicle_Arty-unitID_40"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_40"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_40"]["y"] = -87303.796875
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_40"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_61"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_61"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_61"]["x"] = -245178.140625
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_61"]["Name"] = "MLRS-Vehicle_Arty-unitID_61"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_61"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_61"]["y"] = -87362.1484375
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_61"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_35"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_35"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_35"]["x"] = -245426.859375
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_35"]["Name"] = "MLRS-Vehicle_Arty-unitID_35"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_35"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_35"]["y"] = -87572.84375
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_35"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_31"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_31"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_31"]["x"] = -245839.59375
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_31"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_31"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_31"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_31"]["y"] = -70986.265625
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_31"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_53"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_53"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_53"]["x"] = -246360.203125
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_53"]["Name"] = "MLRS-Vehicle_Arty-unitID_53"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_53"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_53"]["y"] = -85803.765625
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_53"]["Dead"] = true
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_63"] = {}
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_63"]["Coalition"] = 2
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_63"]["x"] = -245199.546875
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_63"]["Name"] = "MLRS-Vehicle_Arty-unitID_63"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_63"]["Type"] = "MLRS"
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_63"]["y"] = -87417.8828125
GroundGroupsDestroyed["MLRS-Vehicle_Arty-unitID_63"]["Dead"] = true
GroundGroupsDestroyed["Ground-3-3"] = {}
GroundGroupsDestroyed["Ground-3-3"]["Coalition"] = 1
GroundGroupsDestroyed["Ground-3-3"]["x"] = -244098.515625
GroundGroupsDestroyed["Ground-3-3"]["Name"] = "Ground-3-3"
GroundGroupsDestroyed["Ground-3-3"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Ground-3-3"]["y"] = -87553.7578125
GroundGroupsDestroyed["Ground-3-3"]["Dead"] = true
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_71"] = {}
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_71"]["Coalition"] = 1
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_71"]["x"] = -245612.95852071
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_71"]["Name"] = "Soldier AK-Vehicle_Infantery-unitID_71"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_71"]["Type"] = "Soldier AK"
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_71"]["y"] = -71249.289614046
GroundGroupsDestroyed["Soldier AK-Vehicle_Infantery-unitID_71"]["Dead"] = true
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_59"] = {}
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_59"]["Coalition"] = 2
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_59"]["x"] = -244593.8790296
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_59"]["Name"] = "Leclerc_XXI-Vehicle_Armor_Heavy-unitID_59"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_59"]["Type"] = "Leclerc_XXI"
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_59"]["y"] = -87645.369591535
GroundGroupsDestroyed["Leclerc_XXI-Vehicle_Armor_Heavy-unitID_59"]["Dead"] = true
